name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            asset_name: app-linux
          - os: macos-latest
            asset_name: app-macos
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up GraalVM 23
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '23'
        cache: maven
    - name: Build with Maven
      run: mvn package
