name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            prefix_name: linux
          - os: macos-latest
            prefix_name: macos
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up GraalVM 23
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '23'
        cache: maven

    - name: Get VERSION from tag or commit
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        fi    

    - name: Build Native Image
      run: |
        mvn -B -Pnative package
        cp target/jenius-*.jar jenius-${{ env.VERSION }}.jar
        cp target/jenius jenius-${{ env.VERSION }}-${{ matrix.prefix_name }}

    - name: Upload Java Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jenius-java
        path: jenius-*.jar
        overwrite: true

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jenius-${{ matrix.prefix_name }}
        path: jenius-*-${{ matrix.prefix_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          jenius-java/*
          jenius-linux/*
          jenius-macos/*
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: true
