name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            prefix_name: linux
          - os: macos-latest
            prefix_name: macos
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up GraalVM 23
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '23'
        cache: maven

    - name: Build Native Image
      run: mvn -B -Pnative package

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.prefix_name }}-jenius
        path: target/jenius

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/linux-jenius
          dist/macos-jenius
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: true
