name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up GraalVM 23
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '23'
        cache: maven
    - name: Build with Maven
      run: mvn package
