name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        include:
          - os: ubuntu-latest
            folder_name: linux
          - os: macos-latest
            folder_name: macos
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up GraalVM 23
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '23'
        cache: maven

    - name: Build Java jar
      run: mvn -B package

    - name: Build Native Image
      run: mvn -B -Pnative -DskipTests package

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.folder_name }}/jenius
        path: target/jenius

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          linux/*
          macos/*
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        generate_release_notes: true
